/**
 * Report generation service for clinical records export
 */
class ReportService {
  /**
   * Format text report for an individual wound entry
   */
  generateEntryReport(entry, user) {
    const assessmentDetails = typeof entry.assessment_details === 'string'
      ? JSON.parse(entry.assessment_details)
      : (entry.assessment_details || {});

    const segData = typeof entry.segmentation_data === 'string'
      ? JSON.parse(entry.segmentation_data)
      : (entry.segmentation_data || {});

    const dateFormatted = new Date(entry.entry_date || entry.created_at).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    const areaCm2Display = entry.wound_area_cm2 != null
      ? `${Number(entry.wound_area_cm2).toFixed(2)} cm²`
      : 'Physical size unavailable—add a scale reference';

    const painDisplay = entry.pain_score != null ? `${entry.pain_score} / 10 (Patient reported)` : 'Not reported';
    const swellingDisplay = entry.swelling_level || 'Not reported (Patient reported)';
    const rednessDisplay = entry.redness_status || 'Not reported (Patient reported)';

    return `
===============================================================
               HEALTRACKS CLINICAL LOG REPORT
===============================================================

PATIENT INFORMATION
---------------------------------------------------------------
Patient Name   : ${user.name}
Patient Email  : ${user.email}
Report Date    : ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

WOUND RECORD DETAILS
---------------------------------------------------------------
Record ID      : ${entry.id}
Wound Case     : ${entry.wound_title || 'Wound Assessment'}
Anatomic Site  : ${entry.wound_location || 'Unspecified site'}
Entry Type     : ${entry.is_followup ? 'Follow-up Tracking Photo' : 'Initial Baseline Photo'}
Captured On    : ${dateFormatted}
Status         : ${entry.wound_status || 'Active'}

PATIENT-REPORTED SYMPTOMS
---------------------------------------------------------------
Pain Score     : ${painDisplay}
Swelling Level : ${swellingDisplay}
Spreading Red  : ${rednessDisplay}

QUANTITATIVE MEASUREMENTS
---------------------------------------------------------------
Estimated 2D Area : ${areaCm2Display}
Boundary Review   : ${segData.isConfirmed ? 'Explicitly Reviewed & Confirmed' : 'Unconfirmed Draft'}
Calibration Status: ${segData.isScaleConfirmed ? 'Calibrated with Scale Reference' : 'Uncalibrated (Physical Size Unavailable)'}

PATIENT NOTES
---------------------------------------------------------------
${entry.notes || 'No user notes entered.'}

ASSESSMENT STATUS
---------------------------------------------------------------
Summary        : ${entry.assessment_summary || 'Structured Assessment Saved'}
System Status  : ${entry.assessment_status || 'completed'}

DISCLAIMER
---------------------------------------------------------------
HealTracks is a wound-documentation and progress-tracking tool.
This report presents estimated 2D measurements and patient-reported
symptoms. It does not constitute a clinical diagnosis or medical
prescription.

===============================================================
Generated by HealTracks Health Platform
===============================================================
    `.trim();
  }
}

module.exports = new ReportService();
